"""
Core arithmetic objects for the localized Bost--Connes systems.

Everything here is finite/computable: we work with Dirichlet characters modulo
a modulus M, with finite truncations of prime sets S, and with the partial sums
of the series appearing in the obstruction group

    Xi_beta(K,S) = { chi : sum_{p in S} N(p)^{-beta} |1 - chi(sigma_p)|^2 < oo }.

Reference: Definition (1.1) and Theorem 3.6 of the manuscript.
"""

from __future__ import annotations

import cmath
import math
from dataclasses import dataclass
from typing import Callable, Iterable, Iterator, Sequence


# ---------------------------------------------------------------- primes ----

def is_prime(n: int) -> bool:
    """Deterministic Miller-Rabin, valid for n < 3.3e24."""
    if n < 2:
        return False
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % p == 0:
            return n == p
    d, s = n - 1, 0
    while d % 2 == 0:
        d //= 2
        s += 1
    for a in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _ in range(s - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def primes_upto(x: int) -> list[int]:
    """Sieve of Eratosthenes."""
    if x < 2:
        return []
    sieve = bytearray([1]) * (x + 1)
    sieve[0:2] = b"\x00\x00"
    for i in range(2, int(x**0.5) + 1):
        if sieve[i]:
            sieve[i * i :: i] = bytearray(len(sieve[i * i :: i]))
    return [i for i in range(x + 1) if sieve[i]]


def primes_in_class(a: int, M: int, x: int) -> list[int]:
    """Primes p <= x with p = a mod M."""
    a %= M
    return [p for p in primes_upto(x) if p % M == a]


# ------------------------------------------------------ Dirichlet characters ----

def unit_group(M: int) -> list[int]:
    return [a for a in range(1, M + 1) if math.gcd(a, M) == 1]


def generated_subgroup(M: int, gens: Iterable[int]) -> set[int]:
    """Subgroup of (Z/MZ)^* generated by `gens`."""
    cur = {1 % M}
    gens = [g % M for g in gens if math.gcd(g, M) == 1]
    while True:
        new = {(x * y) % M for x in cur for y in gens} | cur
        if new == cur:
            return cur
        cur = new


@dataclass(frozen=True)
class DirichletCharacter:
    """A Dirichlet character mod M, given by its values on (Z/MZ)^*."""

    modulus: int
    values: tuple[complex, ...]  # indexed by residue 0..M-1; 0 off the units

    def __call__(self, n: int) -> complex:
        return self.values[n % self.modulus]

    def is_trivial(self) -> bool:
        return all(
            abs(self(a) - 1) < 1e-9 for a in unit_group(self.modulus)
        )

    def order(self) -> int:
        k = 1
        while True:
            if all(abs(self(a) ** k - 1) < 1e-9 for a in unit_group(self.modulus)):
                return k
            k += 1

    def kernel(self) -> set[int]:
        return {a for a in unit_group(self.modulus) if abs(self(a) - 1) < 1e-9}


def all_characters(M: int) -> list[DirichletCharacter]:
    """All characters of (Z/MZ)^*, via a decomposition into cyclic factors."""
    U = unit_group(M)
    n = len(U)
    if n == 0:
        return []
    # Build the group table and find an independent generating set greedily.
    gens: list[int] = []
    orders: list[int] = []
    covered = {1 % M}
    for a in U:
        if a in covered:
            continue
        # order of a
        o, x = 1, a % M
        while x != 1 % M:
            x = x * a % M
            o += 1
        newcov = {(c * pow(a, k, M)) % M for c in covered for k in range(o)}
        if len(newcov) == len(covered) * o:  # independent
            gens.append(a)
            orders.append(o)
            covered = newcov
        if len(covered) == n:
            break
    assert len(covered) == n, f"failed to decompose (Z/{M}Z)^*"

    # Discrete log of each unit with respect to `gens`.
    dlog: dict[int, tuple[int, ...]] = {}
    def rec(i: int, val: int, exps: tuple[int, ...]) -> None:
        if i == len(gens):
            dlog[val] = exps
            return
        g, o = gens[i], orders[i]
        cur = val
        for k in range(o):
            rec(i + 1, cur, exps + (k,))
            cur = cur * g % M
    rec(0, 1 % M, ())

    chars = []
    def build(i: int, choice: tuple[int, ...]) -> None:
        if i == len(gens):
            vals = [0j] * M
            for a in U:
                e = dlog[a]
                z = 1 + 0j
                for j, k in enumerate(e):
                    z *= cmath.exp(2j * math.pi * choice[j] * k / orders[j])
                vals[a % M] = z
            chars.append(DirichletCharacter(M, tuple(vals)))
            return
        for c in range(orders[i]):
            build(i + 1, choice + (c,))
    build(0, ())
    return chars


def quadratic_character(M: int) -> DirichletCharacter:
    """The unique quadratic character mod M, for M with cyclic (Z/MZ)^*."""
    cands = [c for c in all_characters(M) if c.order() == 2]
    if len(cands) != 1:
        raise ValueError(f"(Z/{M}Z)^* has {len(cands)} quadratic characters")
    return cands[0]


# ------------------------------------------------- the obstruction criterion ----

def xi_term(chi: DirichletCharacter, p: int, beta: float, norm: int | None = None) -> float:
    """The summand N(p)^{-beta} |1 - chi(p)|^2 of (1.1)."""
    Np = norm if norm is not None else p
    return Np ** (-beta) * abs(1 - chi(p)) ** 2


def xi_partial_sum(
    chi: DirichletCharacter,
    S: Sequence[int],
    beta: float,
    norms: Sequence[int] | None = None,
) -> float:
    """Partial sum of (1.1) over a finite truncation of S."""
    if norms is None:
        norms = S
    return sum(xi_term(chi, p, beta, N) for p, N in zip(S, norms))


def detecting_set(chi: DirichletCharacter, S: Sequence[int]) -> list[int]:
    """R_chi = { p in S : chi(sigma_p) != 1 }, the primes that detect chi."""
    return [p for p in S if abs(chi(p) - 1) > 1e-9]


# ------------------------------------------------------------ prime sets ----

def sparse_set(residue: int, modulus: int, exponent: float, bound: int) -> list[int]:
    """
    Primes = `residue` mod `modulus`, thinned to counting function ~ x^exponent.

    Greedy selection of one prime of the class in each interval
    [m^{1/e}, 2 m^{1/e}], as in the proof of Proposition 4.15.
    """
    pool = primes_in_class(residue, modulus, bound)
    out: list[int] = []
    m = 1
    while True:
        lo = m ** (1.0 / exponent)
        if lo > bound:
            break
        hi = 2 * lo
        cand = [p for p in pool if lo <= p <= hi and p not in out]
        if cand:
            out.append(cand[0])
        m += 1
    return sorted(out)


def doubly_exponential_set(residue: int, modulus: int, count: int) -> list[int]:
    """
    Primes = `residue` mod `modulus` with p_k > 2^(2^k): summable for every
    beta > 0. Used in Definition 4.5 and Example 4.2.
    """
    out: list[int] = []
    for k in range(1, count + 1):
        n = 2 ** (2**k) + 1
        # search upward; for k >= 5 this is only symbolic, so cap the work
        if k > 5:
            break
        while True:
            if n % modulus == residue % modulus and is_prime(n):
                out.append(n)
                break
            n += 1
    return out


def sophie_germain_upto(x: int) -> list[int]:
    """p with 2p+1 also prime."""
    ps = primes_upto(2 * x + 1)
    pset = set(ps)
    return [p for p in ps if p <= x and (2 * p + 1) in pset]


# -------------------------------------------- the invariant Psi (Prop 4.12) ----

def legendre_mod3(u: int) -> int:
    """(u/3) for u coprime to 3."""
    return 1 if u % 3 == 1 else -1


@dataclass
class AdelicPoint:
    """
    A point of the conull part of hat(Z)_S in the coordinates of Lemma 2.9,
    truncated to the data that Psi actually depends on: the unit u_3 and the
    valuations at the primes of R.
    """

    u3: int                     # a unit of Z_3, tracked mod 9
    vR: dict[int, int]          # valuations at primes of R

    def multiply(self, ell: int, R: Sequence[int]) -> "AdelicPoint":
        """Multiplication by a prime ell of S."""
        vR = dict(self.vR)
        if ell == 3:
            return AdelicPoint(self.u3, vR)   # (theta_3)_3 = 1
        if ell in R:
            vR[ell] = vR.get(ell, 0) + 1
        return AdelicPoint((self.u3 * ell) % 9, vR)

    def psi(self) -> int:
        """Psi(x) of equation (4.1)."""
        return legendre_mod3(self.u3) * (-1) ** sum(self.vR.values())


# ------------------------------------------------------- misc arithmetic ----

def admissible_classes(M: int) -> list[int]:
    """A_M = { a in (Z/MZ)^* : 2a+1 in (Z/MZ)^* }, Lemma 5.6."""
    return [a for a in unit_group(M) if math.gcd(2 * a + 1, M) == 1]


def represented_by(n: int, a: int, b: int) -> bool:
    """Is n = a x^2 + b y^2 solvable in integers?"""
    y = 0
    while b * y * y <= n:
        r = n - b * y * y
        if r % a == 0:
            q = r // a
            s = math.isqrt(q)
            if s * s == q:
                return True
        y += 1
    return False


def m_p(t: float, c: complex) -> complex:
    """m_p = (1-t)/(1-c t), the quantity of Lemma 3.2."""
    return (1 - t) / (1 - c * t)
